export const OFFICIAL_MIT_DEPARTMENTS = [
  { code: "CSE", name: "Computer Science & Engineering", school: "School of Computer Engineering", building: "AB5" },
  { code: "IT", name: "Information Technology", school: "School of Computer Engineering", building: "AB5" },
  { code: "DSE", name: "Data Science & Engineering", school: "School of Computer Engineering", building: "AB5" },
  { code: "AIML", name: "Artificial Intelligence & Machine Learning", school: "School of Computer Engineering", building: "AB5" },
  { code: "CCE", name: "Computer & Communication Engineering", school: "School of Computer Engineering", building: "AB5" },
  { code: "ECE", name: "Electronics & Communication Engineering", school: "School of Electrical & Electronics", building: "AB3" },
  { code: "EEE", name: "Electrical & Electronics Engineering", school: "School of Electrical & Electronics", building: "AB3" },
  { code: "EIE", name: "Electronics & Instrumentation Engineering", school: "School of Electrical & Electronics", building: "AB3" },
  { code: "BME", name: "Biomedical Engineering", school: "School of Electrical & Electronics", building: "AB3" },
  { code: "ME", name: "Mechanical Engineering", school: "School of Mechanical & Industrial", building: "AB1" },
  { code: "MTE", name: "Mechatronics Engineering", school: "School of Mechanical & Industrial", building: "AB1" },
  { code: "AE", name: "Aeronautical Engineering", school: "School of Mechanical & Industrial", building: "AB1" },
  { code: "AME", name: "Automobile Engineering", school: "School of Mechanical & Industrial", building: "AB1" },
  { code: "IP", name: "Industrial & Production Engineering", school: "School of Mechanical & Industrial", building: "AB1" },
  { code: "CE", name: "Civil Engineering", school: "School of Civil & Chemical", building: "AB2" },
  { code: "CHE", name: "Chemical Engineering", school: "School of Civil & Chemical", building: "AB2" },
  { code: "BT", name: "Biotechnology", school: "School of Basic & Applied Sciences", building: "AB4" },
  { code: "H&M", name: "Humanities & Management", school: "School of Management", building: "AB5" },
  { code: "MATH", name: "Mathematics & Basic Sciences", school: "School of Basic & Applied Sciences", building: "AB5" },
];
